#!/bin/bash

# Path to your minishell binary
MINISHELL="./minishell"

# Temporary files for storing output
BASH_OUT="dollar_sign_bash_output.txt"
MINISHELL_OUT="dollar_sign_minishell_output.txt"

# List of commands to test
TEST_COMMANDS=(
'echo $'
'echo $?'
'echo $?$'
'echo $? | echo $? | echo $?'
'echo $:$= | cat -e'
'echo " $ " | cat -e'
'echo ' $ ' | cat -e'
'echo $HOME'
'echo \$HOME'
'echo my shit terminal is [$TERM]'
'echo my shit terminal is [$TERM4'
'echo my shit terminal is [$TERM4]'
'echo $UID'
'echo $HOME9'
'echo $9HOME'
'echo $HOME%'
'echo $UID$HOME'
'echo Le path de mon HOME est $HOME'
'echo $USER$var\$USER$USER\$USERtest$USER'
'echo $hola*'
'echo -nnnn $hola'
'echo $*'
'echo $hola*'
'echo $HOME*'
'echo $""'
'echo "$"""'
'echo '$''''
'echo $"HOME"'
'echo $''HOME'
'echo $""HOME'
'echo "$HO"ME'
'echo '$HO'ME'
'echo "$HO""ME"'
'echo '$HO''ME''
'echo "'$HO''ME'"'
'echo ""$HOME'
'echo "" $HOME'
'echo ''$HOME'
'echo '' $HOME'
'echo $"HO""ME"'
'echo $'HO''ME''
'echo $'HOME''
'echo "$"HOME'
'echo $=HOME'
'echo $"HOLA"'
'echo $'HOLA''
'echo $DONTEXIST Hola'
'echo "$DONTEXIST"Makefile'
'echo "$DONTEXIST""Makefile"'
'echo "$DONTEXIST" "Makefile"'
'$?'
'$?$?'
'?$HOME'
'$'
'$HOME'
'$HOMEdskjhfkdshfsd'
'$HOMEdskjhfkdshfsd'
'$HOMEdskjhfkdshfsd''
'$DONTEXIST'
'$LESS$VAR'
'export $DONTEXIST'
'export $?'
'export HOL\\\$A=bonjour'
'export HO$?LA=bonjour'
'env'
'export HOLA=$HOME'
'env'
'export HOLA=bonjour$HOME'
'env'
'export HOLA=$HOMEbonjour'
'env'
'export HOLA=bon$jour'
'env'
'export HOLA$USER=bonjour'
'env'
'export HOLA=bonjour=casse-toi'
'echo $HOLA'
'export "HOLA=bonjour"=casse-toi'
'echo $HOLA'
'export HOLA=bonjour'
'export BYE=casse-toi'
'echo $HOLA et $BYE'
'export HOLA=bonjour BYE=casse-toi'
'echo $HOLA et $BYE'
'export A=a B=b C=c'
'echo $A $B $C'
'export $HOLA=bonjour'
'env'
'export HOLA="bonjour " '
'echo $HOLA'
'export HOLA="bonjour "/'
'echo $HOLA'
'export HOLA='"''
'c$HOLA Makefile'
'export HOLA="cat Makefile | grep NAME" '
'echo $HOLA'
'export HOLA=hey '
'echo $HOLA$HOLA$HOLA=hey$HOLA'
'export HOLA=" bonjour hey " '
'export HOLA=" bonjour hey " '
''echo """$HOLA""" | cat -e'
'export HOLA=" bonjour hey " '
'echo wesh"$HOLA" | cat -e'
'export HOLA=" bonjour hey " '
'echo wesh""$HOLA.'
'export HOLA=" bonjour hey " '
'echo wesh$""HOLA.'
'export HOLA=" bonjour hey " '
'echo wesh$"HOLA HOLA".'
'export HOLA=bonjour'
'export HOLA=" hola et $HOLA"'
'echo $HOLA'
'export HOLA=bonjour'
'export HOLA=' hola et $HOLA''
'echo $HOLA'
'export HOLA=bonjour'
'export HOLA=" hola et $HOLA"$HOLA'
'echo $HOLA'
'export HOLA="ls -l - a"'
'echo $HOLA'
'export HOLA="s -la" '
'l$HOLA'
'export HOLA="s -la" '
'l"$HOLA"'
'export HOLA="s -la" '
'l'$HOLA''
'export HOLA="l" '
'$HOLAs'
'export HOLA="l" '
'$HOLAs'
'export HOLA="l" '
''$HOLA's'
'export HOLA=p'
'export BYE=w'
'$HOLA"BYE"d'
'export HOLA=p'
'export BYE=w'
'$HOLA'$BYE'd'
'export HOLA=p'
'export BYE=w'
'$HOLA"$BYEd'
'export HOLA=p'
'export BYE=w'
'$"HOLA"$"BYE"d'
'export HOLA=p'
'export BYE=w'
'$'HOLA'$'BYE'd'
'export HOLA=-n'
'echo $HOLA hey'
'export A=1 B=2 C=3 D=4 E=5 F=6 G=7 H=8'
'echo "$A'$B"'$C"$D'$E'"$F'"'$G'$H"'
'unset PATH'
'echo $PATH'
'pwd'
'unset PWD'
'env | grep PWD'
'cd $PWD'
'pwd'
'unset $HOLA'
'unset $PWD'
'unset HOL$?A'
'unset PATH'
'echo $PATH'
'export hola | unset hola | echo $?'
'cd $HOME'
'cd $HOME $HOME'
'cd $HOME/42_works'
'cd "$PWD/srcs"'
'cd '$PWD/srcs''
'unset HOME'
'cd $HOME'
'cd / | echo $?'
'pwd'
'cd ~/ | echo $?'
'pwd'
'mkdir a'
'mkdir a/b'
'cd a/b'
'rm -r ../../a'
'echo $PWD'
'echo $OLDPWD'
'mkdir a'
'mkdir a/b'
'cd a/b'
'rm -r ../../a'
'cd'
'echo $PWD'
'echo $OLDPWD'
'mkdir a'
'cd a'
'rm -r ../a'
'echo $PWD'
'echo $OLDPWD'
'export CDPATH=/'
'cd $HOME/..'
'expr $? + $?'
'whoami | grep $USER'
'whoami | grep $USER > /tmp/bonjour'
'cat /tmp/bonjour'
'export HOLA=hey'
'echo bonjour > $HOLA'
'echo $HOLA'
'export HOLA="bonjour hello"'
'>$HOLA'
'ls'
'export HOLA="bonjour hello"'
'>"$HOLA"'
'ls'
'export HOLA="bonjour hello"'
'>$"HOLA"'
'ls'
'export HOLA="bonjour hello"'
'>$HOLA>hey'
'ls'
'export HOLA="bonjour hello"'
'>hey>$HOLA'
'ls'
'export HOLA="bonjour hello"'
'>hey>$HOLA>hey>hey'
'ls'
'export A=hey'
'export A B=Hola D E C="Que Tal"'
'echo $PROUT$B$C > /tmp/a > /tmp/b > /tmp/c'
'cat /tmp/a'
'cat /tmp/b'
'cat /tmp/c'
'cat << $HOME'
'<< $hola'
'<< $"hola"$"b"'
'<< $"$hola"$$"b"'
'<< ho$la$"$a"$$"b"'
"
)

counter=1

# Run tests
echo "Running tests..."
for cmd in "${TEST_COMMANDS[@]}"; do
    # Run command in Bash and save output
    #echo "[$counter] cmd:$cmd cmdend" >> "$BASH_OUT"
    #echo "$cmd" | bash >> "$BASH_OUT" 2>&1
	#echo "[$counter]------------------------" >> "$BASH_OUT"

    # Run command in Minishell and save output
    echo "[$counter]-----------------" >> "$MINISHELL_OUT"
    echo "$cmd" | $MINISHELL >> "$MINISHELL_OUT" 2>&1
    	echo "[$counter]-----------------------" >> "$MINISHELL_OUT"

	((counter++))
    # Compare outputs
    if diff -q "$BASH_OUT" "$MINISHELL_OUT" > /dev/null; then
        echo "[✅] Test passed: $cmd"
    else
        echo "[❌] Test failed: $cmd"
	sleep 0.05
echo "Expected output:"
    cat "$BASH_OUT"
    echo "Your minishell output:"
    cat "$MINISHELL_OUT"
    fi
done

# Cleanup temporary files
#rm -f "$BASH_OUT" "$MINISHELL_OUT"

echo "Testing completed!"

